/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vfeg.erbr.gui;



import com.vfeg.erbr.configuration.AppConf;
import com.vfeg.erbr.main.Processor;
import com.vfeg.erbr.mongo.MongoClient;
import java.awt.Image;
import java.io.IOException;
import java.io.PrintStream;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eelaamr
 */
public class ERBR extends javax.swing.JFrame {

    
    /**
     * Creates new form ERBR
     */
    public ERBR() {
        initComponents();
        System.out.println("Components Initialized");
        Ericssonize();
        System.out.println("Ericssonized");
        initApp();
        System.out.println("App Initialized");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        EricssonLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lineSpectrum = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        loadRehomingBtn = new javax.swing.JButton();
        checkDbBtn = new javax.swing.JButton();
        updateClientBtn = new javax.swing.JButton();
        dumpLogBtn = new javax.swing.JButton();
        generateXmlBtn = new javax.swing.JButton();
        generateXmlBtn1 = new javax.swing.JButton();
        loadRehomingBtn1 = new javax.swing.JButton();
        paramterAdjustment = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        databaseStatus = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RehomingFilePathLabel = new javax.swing.JLabel();
        WorkingDirLabel = new javax.swing.JLabel();
        RehomingFilePath = new javax.swing.JLabel();
        WorkingDir = new javax.swing.JLabel();
        RehomingPlanBtn = new javax.swing.JButton();
        WorkingDirBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        RehomingFilePathLabel1 = new javax.swing.JLabel();
        WorkingDirLabel1 = new javax.swing.JLabel();
        RehomingFilePath1 = new javax.swing.JLabel();
        WorkingDir1 = new javax.swing.JLabel();
        RehomingPlanBtn1 = new javax.swing.JButton();
        WorkingDirBtn1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logging = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lastUtranCellOSS1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastUtranRelationOSS1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastUtranRelationOSS3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastUtranCellOSS2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastUtranRelationOSS2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lastUtranRelationOSS4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        WorkingDirLabel2 = new javax.swing.JLabel();
        paramterWorkingDirPath = new javax.swing.JLabel();
        paramterWorkingDirBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ERBR");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        EricssonLogo.setLabelFor(EricssonLogo);

        jLabel1.setFont(new java.awt.Font("Ericsson Capital TT", 0, 20)); // NOI18N
        jLabel1.setText("Ericsson Border Relations Tool");

        lineSpectrum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vfeg/erbr/gui/lineSpectrum.png"))); // NOI18N
        lineSpectrum.setText("jLabel2");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        loadRehomingBtn.setText("Load Rehoming Plan");
        loadRehomingBtn.setEnabled(false);
        loadRehomingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRehomingBtnActionPerformed(evt);
            }
        });

        checkDbBtn.setText("Check DB Connectivity");
        checkDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDbBtnActionPerformed(evt);
            }
        });

        updateClientBtn.setText("Update Client Status");
        updateClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClientBtnActionPerformed(evt);
            }
        });

        dumpLogBtn.setText("Dump Log File");
        dumpLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dumpLogBtnActionPerformed(evt);
            }
        });

        generateXmlBtn.setText("Generate Rehoming Plan");
        generateXmlBtn.setEnabled(false);
        generateXmlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateXmlBtnActionPerformed(evt);
            }
        });

        generateXmlBtn1.setText("Generate New Site Relations");
        generateXmlBtn1.setEnabled(false);
        generateXmlBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateXmlBtn1ActionPerformed(evt);
            }
        });

        loadRehomingBtn1.setText("Load New Site Relations");
        loadRehomingBtn1.setEnabled(false);
        loadRehomingBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRehomingBtn1ActionPerformed(evt);
            }
        });

        paramterAdjustment.setText("Adjust uarfcnUl");
        paramterAdjustment.setEnabled(false);
        paramterAdjustment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramterAdjustmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadRehomingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(checkDbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateClientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dumpLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generateXmlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generateXmlBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addComponent(loadRehomingBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paramterAdjustment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadRehomingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadRehomingBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDbBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateClientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dumpLogBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateXmlBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateXmlBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramterAdjustment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Database:");

        databaseStatus.setText("N/A");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rehoming Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        RehomingFilePathLabel.setText("Rehoming Plan (CSV) :");

        WorkingDirLabel.setText("Working Directory:");

        RehomingFilePath.setForeground(new java.awt.Color(153, 153, 153));
        RehomingFilePath.setText("Please browse for rehoming file CSV");

        WorkingDir.setForeground(new java.awt.Color(153, 153, 153));
        WorkingDir.setText("Please browse for working directory DIR");

        RehomingPlanBtn.setText("Browse");
        RehomingPlanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RehomingPlanBtnActionPerformed(evt);
            }
        });

        WorkingDirBtn.setText("Browse");
        WorkingDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingDirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(RehomingFilePathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RehomingFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(WorkingDirLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkingDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(RehomingPlanBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkingDirBtn)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RehomingFilePathLabel)
                    .addComponent(RehomingFilePath)
                    .addComponent(RehomingPlanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkingDirLabel)
                    .addComponent(WorkingDir)
                    .addComponent(WorkingDirBtn))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rehoming", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Site Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        RehomingFilePathLabel1.setText("New Site Relations (CSV):");

        WorkingDirLabel1.setText("Working Directory:");

        RehomingFilePath1.setForeground(new java.awt.Color(153, 153, 153));
        RehomingFilePath1.setText("Please browse for new site file CSV");

        WorkingDir1.setForeground(new java.awt.Color(153, 153, 153));
        WorkingDir1.setText("Please browse for working directory DIR");

        RehomingPlanBtn1.setText("Browse");
        RehomingPlanBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RehomingPlanBtn1ActionPerformed(evt);
            }
        });

        WorkingDirBtn1.setText("Browse");
        WorkingDirBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingDirBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(RehomingFilePathLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RehomingFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(WorkingDirLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkingDir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(RehomingPlanBtn1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WorkingDirBtn1)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RehomingFilePathLabel1)
                    .addComponent(RehomingFilePath1)
                    .addComponent(RehomingPlanBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkingDirLabel1)
                    .addComponent(WorkingDir1)
                    .addComponent(WorkingDirBtn1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Site", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Application Log", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        logging.setEditable(false);
        logging.setColumns(20);
        logging.setLineWrap(true);
        logging.setRows(5);
        logging.setWrapStyleWord(true);
        jScrollPane1.setViewportView(logging);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("App Log", jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Last UtranCell [Delta]:");

        lastUtranCellOSS1.setText("N/A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Last UtranRelation [Delta]:");

        lastUtranRelationOSS1.setText("N/A");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Last ExternalUtranCell [Delta]:");

        lastUtranRelationOSS3.setText("N/A");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Last UtranCell [Cairo]:");

        lastUtranCellOSS2.setText("N/A");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Last UtranRelation [Cairo]:");

        lastUtranRelationOSS2.setText("N/A");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Last ExternalUtranCell [Cairo]:");

        lastUtranRelationOSS4.setText("N/A");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastUtranCellOSS2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastUtranRelationOSS2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastUtranRelationOSS4)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lastUtranCellOSS1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lastUtranRelationOSS1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastUtranRelationOSS3)
                            .addComponent(jLabel8))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranRelationOSS1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranCellOSS1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranRelationOSS3)))
                .addGap(49, 49, 49)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranCellOSS2))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranRelationOSS2))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastUtranRelationOSS4)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Collection Status", jPanel10);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Paramter Adjustment"));

        WorkingDirLabel2.setText("Working Directory:");

        paramterWorkingDirPath.setForeground(new java.awt.Color(153, 153, 153));
        paramterWorkingDirPath.setText("Please browse for working directory DIR");

        paramterWorkingDirBtn.setText("Browse");
        paramterWorkingDirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramterWorkingDirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WorkingDirLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramterWorkingDirPath, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramterWorkingDirBtn))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkingDirLabel2)
                    .addComponent(paramterWorkingDirPath)
                    .addComponent(paramterWorkingDirBtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paramter Adjustment", jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EricssonLogo)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineSpectrum, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(databaseStatus))
                                        .addGap(0, 178, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(EricssonLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineSpectrum)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(databaseStatus)
                        .addGap(59, 59, 59))))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void RehomingPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RehomingPlanBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            RehomingFilePath.setText(fileChooser.getSelectedFile().getAbsolutePath());
            updateRehomingAndGenerationBtnStatus();
        }
    }//GEN-LAST:event_RehomingPlanBtnActionPerformed

    private void WorkingDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingDirBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            WorkingDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
            updateRehomingAndGenerationBtnStatus();
        }
    }//GEN-LAST:event_WorkingDirBtnActionPerformed

    private void checkDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDbBtnActionPerformed
        databaseStatus.setText(MongoClient.getConnection());
    }//GEN-LAST:event_checkDbBtnActionPerformed

    private void updateClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClientBtnActionPerformed
        if(AppConf.getLastOSSOneUpdateUtranCell()!=null){
        lastUtranCellOSS1.setText(sdf.format(AppConf.getLastOSSOneUpdateUtranCell()));
        }
        if(AppConf.getLastOSSTwoUpdateUtranCell()!=null){
        lastUtranCellOSS2.setText(sdf.format(AppConf.getLastOSSTwoUpdateUtranCell()));
        }
        if(AppConf.getLastOSSOneUpdateUtranRelations()!=null){
        lastUtranRelationOSS1.setText(sdf.format(AppConf.getLastOSSOneUpdateUtranRelations()));
        }
        if(AppConf.getLastOSSTwoUpdateUtranRelations()!=null){
        lastUtranRelationOSS2.setText(sdf.format(AppConf.getLastOSSTwoUpdateUtranRelations()));
        }
    }//GEN-LAST:event_updateClientBtnActionPerformed

    private void loadRehomingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRehomingBtnActionPerformed
        processor.setCutoverPlanPath(RehomingFilePath.getText());
        RehomingPlanBtn.setEnabled(false);
        processor.readCutoverFile();
        RehomingPlanBtn.setEnabled(true);
    }//GEN-LAST:event_loadRehomingBtnActionPerformed

    private void generateXmlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateXmlBtnActionPerformed
        generateXmlBtn.setEnabled(false);
        processor.setWorkingDir(WorkingDir.getText());
        new Thread(){
            @Override
            public void run() {
                processor.createRunDirs();
                processor.doCutover();
                generateXmlBtn.setEnabled(true);
            }
            
        }.start();
        
    }//GEN-LAST:event_generateXmlBtnActionPerformed

    private void dumpLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dumpLogBtnActionPerformed
        String message = processor.dumpLogFile();
        JOptionPane.showConfirmDialog(null, message);
    }//GEN-LAST:event_dumpLogBtnActionPerformed

    private void generateXmlBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateXmlBtn1ActionPerformed
        generateXmlBtn1.setEnabled(false);
        processor.setWorkingDir(WorkingDir.getText());
        new Thread(){
            @Override
            public void run() {
                processor.createRunDirs();
                processor.doNewSiteRelation();
                generateXmlBtn1.setEnabled(true);
            }
            
        }.start();
    }//GEN-LAST:event_generateXmlBtn1ActionPerformed

    private void RehomingPlanBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RehomingPlanBtn1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            RehomingFilePath1.setText(fileChooser.getSelectedFile().getAbsolutePath());
            updateRehomingAndGenerationBtnStatusNewSite();
        }
    }//GEN-LAST:event_RehomingPlanBtn1ActionPerformed

    private void WorkingDirBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingDirBtn1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            WorkingDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
            WorkingDir1.setText(fileChooser.getSelectedFile().getAbsolutePath());
            updateRehomingAndGenerationBtnStatusNewSite();
        }
    }//GEN-LAST:event_WorkingDirBtn1ActionPerformed

    private void loadRehomingBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRehomingBtn1ActionPerformed
        processor.setNewSiteRelationPlanPath(RehomingFilePath1.getText());
        RehomingPlanBtn1.setEnabled(false);
        processor.readNewSiteFile();
        RehomingPlanBtn1.setEnabled(true);
    }//GEN-LAST:event_loadRehomingBtn1ActionPerformed

    private void paramterAdjustmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramterAdjustmentActionPerformed
        paramterAdjustment.setEnabled(false);
        processor.setWorkingDir(WorkingDir.getText());
        new Thread(){
            @Override
            public void run() {
                processor.createRunDirs();
                processor.doParamterAdjustment();
                paramterAdjustment.setEnabled(true);
            }
            
        }.start();
    }//GEN-LAST:event_paramterAdjustmentActionPerformed

    private void paramterWorkingDirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramterWorkingDirBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            WorkingDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
            paramterWorkingDirPath.setText(fileChooser.getSelectedFile().getAbsolutePath());
            updateParamterAdjustmentBtnStatus();
        }
    }//GEN-LAST:event_paramterWorkingDirBtnActionPerformed

    private void updateRehomingAndGenerationBtnStatus(){
        if( RehomingFilePath.getText().toLowerCase().contains(".csv") && 
                (WorkingDir.getText().toLowerCase().contains("\\") || WorkingDir.getText().toLowerCase().contains("/"))){
            loadRehomingBtn.setEnabled(true);
            generateXmlBtn.setEnabled(true);
        }
    }
    private void updateRehomingAndGenerationBtnStatusNewSite(){
        if( RehomingFilePath1.getText().toLowerCase().contains(".csv") && 
                (WorkingDir.getText().toLowerCase().contains("\\") || WorkingDir.getText().toLowerCase().contains("/"))){
            loadRehomingBtn1.setEnabled(true);
            generateXmlBtn1.setEnabled(true);
        }
    }
    
    private void updateParamterAdjustmentBtnStatus(){
        if((WorkingDir.getText().toLowerCase().contains("\\") || WorkingDir.getText().toLowerCase().contains("/"))){
            paramterAdjustment.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERBR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERBR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EricssonLogo;
    private javax.swing.JLabel RehomingFilePath;
    private javax.swing.JLabel RehomingFilePath1;
    private javax.swing.JLabel RehomingFilePathLabel;
    private javax.swing.JLabel RehomingFilePathLabel1;
    private javax.swing.JButton RehomingPlanBtn;
    private javax.swing.JButton RehomingPlanBtn1;
    private javax.swing.JLabel WorkingDir;
    private javax.swing.JLabel WorkingDir1;
    private javax.swing.JButton WorkingDirBtn;
    private javax.swing.JButton WorkingDirBtn1;
    private javax.swing.JLabel WorkingDirLabel;
    private javax.swing.JLabel WorkingDirLabel1;
    private javax.swing.JLabel WorkingDirLabel2;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton checkDbBtn;
    private javax.swing.JLabel databaseStatus;
    private javax.swing.JButton dumpLogBtn;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton generateXmlBtn;
    private javax.swing.JButton generateXmlBtn1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastUtranCellOSS1;
    private javax.swing.JLabel lastUtranCellOSS2;
    private javax.swing.JLabel lastUtranRelationOSS1;
    private javax.swing.JLabel lastUtranRelationOSS2;
    private javax.swing.JLabel lastUtranRelationOSS3;
    private javax.swing.JLabel lastUtranRelationOSS4;
    private javax.swing.JLabel lineSpectrum;
    private javax.swing.JButton loadRehomingBtn;
    private javax.swing.JButton loadRehomingBtn1;
    private javax.swing.JTextArea logging;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton paramterAdjustment;
    private javax.swing.JButton paramterWorkingDirBtn;
    private javax.swing.JLabel paramterWorkingDirPath;
    private javax.swing.JButton updateClientBtn;
    // End of variables declaration//GEN-END:variables
    private Processor processor = new Processor();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    private void Ericssonize() {
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/com/vfeg/erbr/gui/EricssonLogo.png"));
        icon = new ImageIcon(icon.getImage().getScaledInstance(28, 36,Image.SCALE_DEFAULT));
        EricssonLogo.setIcon(icon);
        try {
            //        try {
            this.setIconImage(ImageIO.read(this.getClass().getResource("/com/vfeg/erbr/gui/favicon.png")));
        } catch (IOException ex) {
            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.setTitle("ERBR v"+AppConf.getAppVersion());
            this.setResizable(false);

//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            SwingUtilities.updateComponentTreeUI(this);
//            updateComponentTreeUI(this);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            Logger.getLogger(ERBR.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void initApp() {
        
        PrintStream printStream = new PrintStream(new CustomOutputStream(logging));
        System.setOut(printStream);
        System.setErr(printStream);
        
        AppConf.setApplicationPath("/home/ERBR/Desktop/ERBR/");
//        AppConf.setApplicationPath("C:\\ericsson\\projects\\VF\\Sales\\ERBR\\ERBR_3.2");
        processor.initializeApp();
        databaseStatus.setText(MongoClient.getConnection());
        if(AppConf.getLastOSSOneUpdateUtranCell()!=null){
        lastUtranCellOSS1.setText(sdf.format(AppConf.getLastOSSOneUpdateUtranCell()));
        }
        if(AppConf.getLastOSSTwoUpdateUtranCell()!=null){
        lastUtranCellOSS2.setText(sdf.format(AppConf.getLastOSSTwoUpdateUtranCell()));
        }
        if(AppConf.getLastOSSOneUpdateUtranRelations()!=null){
        lastUtranRelationOSS1.setText(sdf.format(AppConf.getLastOSSOneUpdateUtranRelations()));
        }
        if(AppConf.getLastOSSTwoUpdateUtranRelations()!=null){
        lastUtranRelationOSS2.setText(sdf.format(AppConf.getLastOSSTwoUpdateUtranRelations()));
        }
        if(AppConf.getLastOSSOneUpdateExternalUtranCell()!=null){
        lastUtranRelationOSS3.setText(sdf.format(AppConf.getLastOSSOneUpdateExternalUtranCell()));
        }
        if(AppConf.getLastOSSTwoUpdateExternalUtranCell()!=null){
        lastUtranRelationOSS4.setText(sdf.format(AppConf.getLastOSSTwoUpdateExternalUtranCell()));
        }
        
    }

}
